[package]
name = "fake"
version = "2.2.2"
authors = ["cksac <cs.cksac@gmail.com>"]
description = "An easy to use library for generating fake data like name, number, address, lorem, dates, etc."
keywords = ["faker", "data", "generator", "random"]
license = "MIT/Apache-2.0"
readme = "README.md"
repository = "https://github.com/cksac/fake-rs"
homepage = "https://github.com/cksac/fake-rs"
edition = "2018"

[dependencies]
dummy = { version = "0.3", optional = true, path = "../dummy_derive" }
rand = "0.7"
chrono = { version = "0.4", optional = true }
http = { version = "0.2", optional = true }
uuid = { version = "0.8", features = ["v4"], optional = true }

[features]
wasm-bindgen = ["rand/wasm-bindgen"]

# Provide derive(Dummy) macros.
derive = ["dummy"]

[[example]]
name = "basic"
path = "examples/basic.rs"
required-features = ["derive"]

[[example]]
name = "derive"
path = "examples/derive.rs"
required-features = ["derive", "http", "chrono"]

[[example]]
name = "usage"
path = "examples/usage.rs"
required-features = ["derive"]